/**
 * Tags Seed Data
 *
 * Initial tags based on available dev icons plus additional popular technologies.
 * These tags will be automatically loaded when the database is initialized or reset.
 */

import { NewTag } from '../schema';

export const tagsSeed: Omit<NewTag, 'id' | 'created_at' | 'updated_at'>[] = [
  // Tags with available icons
  { codeindex: 'aws', name: 'AWS', icon: 'amazonwebservices' },
  { codeindex: 'android', name: 'Android', icon: 'android' },
  { codeindex: 'angular', name: 'Angular', icon: 'angular' },
  { codeindex: 'ansible', name: 'Ansible', icon: 'ansible' },
  { codeindex: 'apache', name: 'Apache', icon: 'apache' },
  { codeindex: 'apache-kafka', name: 'Apache Kafka', icon: 'apachekafka' },
  { codeindex: 'apple', name: 'Apple', icon: 'apple' },
  { codeindex: 'babel', name: 'Babel', icon: 'babel' },
  { codeindex: 'bootstrap', name: 'Bootstrap', icon: 'bootstrap' },
  { codeindex: 'c', name: 'C', icon: 'c' },
  { codeindex: 'cpp', name: 'C++', icon: 'cplusplus' },
  { codeindex: 'css3', name: 'CSS3', icon: 'css3' },
  { codeindex: 'dart', name: 'Dart', icon: 'dart' },
  { codeindex: 'debian', name: 'Debian', icon: 'debian' },
  { codeindex: 'django', name: 'Django', icon: 'django' },
  { codeindex: 'docker', name: 'Docker', icon: 'docker' },
  { codeindex: 'electron', name: 'Electron', icon: 'electron' },
  { codeindex: 'express', name: 'Express', icon: 'express' },
  { codeindex: 'figma', name: 'Figma', icon: 'figma' },
  { codeindex: 'firebase', name: 'Firebase', icon: 'firebase' },
  { codeindex: 'flutter', name: 'Flutter', icon: 'flutter' },
  { codeindex: 'gatsby', name: 'Gatsby', icon: 'gatsby' },
  { codeindex: 'git', name: 'Git', icon: 'git' },
  { codeindex: 'github', name: 'GitHub', icon: 'github' },
  { codeindex: 'gitlab', name: 'GitLab', icon: 'gitlab' },
  { codeindex: 'bash', name: 'Bash', icon: 'gnubash' },
  { codeindex: 'go', name: 'Go', icon: 'go' },
  { codeindex: 'graphql', name: 'GraphQL', icon: 'graphql' },
  { codeindex: 'html5', name: 'HTML5', icon: 'html5' },
  { codeindex: 'javascript', name: 'JavaScript', icon: 'javascript' },
  { codeindex: 'jenkins', name: 'Jenkins', icon: 'jenkins' },
  { codeindex: 'jest', name: 'Jest', icon: 'jest' },
  { codeindex: 'jquery', name: 'jQuery', icon: 'jquery' },
  { codeindex: 'kotlin', name: 'Kotlin', icon: 'kotlin' },
  { codeindex: 'kubernetes', name: 'Kubernetes', icon: 'kubernetes' },
  { codeindex: 'laravel', name: 'Laravel', icon: 'laravel' },
  { codeindex: 'linux', name: 'Linux', icon: 'linux' },
  { codeindex: 'mongodb', name: 'MongoDB', icon: 'mongodb' },
  { codeindex: 'mysql', name: 'MySQL', icon: 'mysql' },
  { codeindex: 'nestjs', name: 'NestJS', icon: 'nestjs' },
  { codeindex: 'nextjs', name: 'Next.js', icon: 'nextdotjs' },
  { codeindex: 'nginx', name: 'Nginx', icon: 'nginx' },
  { codeindex: 'nodejs', name: 'Node.js', icon: 'nodedotjs' },
  { codeindex: 'npm', name: 'NPM', icon: 'npm' },
  { codeindex: 'nuxtjs', name: 'Nuxt.js', icon: 'nuxtdotjs' },
  { codeindex: 'php', name: 'PHP', icon: 'php' },
  { codeindex: 'postgresql', name: 'PostgreSQL', icon: 'postgresql' },
  { codeindex: 'python', name: 'Python', icon: 'python' },
  { codeindex: 'react', name: 'React', icon: 'react' },
  { codeindex: 'redis', name: 'Redis', icon: 'redis' },
  { codeindex: 'redux', name: 'Redux', icon: 'redux' },
  { codeindex: 'ruby', name: 'Ruby', icon: 'ruby' },
  { codeindex: 'rust', name: 'Rust', icon: 'rust' },
  { codeindex: 'sass', name: 'Sass', icon: 'sass' },
  { codeindex: 'spring', name: 'Spring', icon: 'spring' },
  { codeindex: 'sqlite', name: 'SQLite', icon: 'sqlite' },
  { codeindex: 'svelte', name: 'Svelte', icon: 'svelte' },
  { codeindex: 'swift', name: 'Swift', icon: 'swift' },
  { codeindex: 'tailwindcss', name: 'Tailwind CSS', icon: 'tailwindcss' },
  { codeindex: 'typescript', name: 'TypeScript', icon: 'typescript' },
  { codeindex: 'ubuntu', name: 'Ubuntu', icon: 'ubuntu' },
  { codeindex: 'vim', name: 'Vim', icon: 'vim' },
  { codeindex: 'vuejs', name: 'Vue.js', icon: 'vuedotjs' },
  { codeindex: 'webpack', name: 'Webpack', icon: 'webpack' },
  { codeindex: 'wordpress', name: 'WordPress', icon: 'wordpress' },
  { codeindex: 'yarn', name: 'Yarn', icon: 'yarn' },

  // Additional popular technologies without icons
  { codeindex: 'java', name: 'Java', icon: null },
  { codeindex: 'csharp', name: 'C#', icon: null },
  { codeindex: 'dotnet', name: '.NET', icon: null },
  { codeindex: 'scala', name: 'Scala', icon: null },
  { codeindex: 'perl', name: 'Perl', icon: null },
  { codeindex: 'r', name: 'R', icon: null },
  { codeindex: 'matlab', name: 'MATLAB', icon: null },
  { codeindex: 'elixir', name: 'Elixir', icon: null },
  { codeindex: 'erlang', name: 'Erlang', icon: null },
  { codeindex: 'haskell', name: 'Haskell', icon: null },
  { codeindex: 'clojure', name: 'Clojure', icon: null },
  { codeindex: 'solidity', name: 'Solidity', icon: null },
  { codeindex: 'terraform', name: 'Terraform', icon: null },
  { codeindex: 'fastapi', name: 'FastAPI', icon: null },
  { codeindex: 'flask', name: 'Flask', icon: null },
  { codeindex: 'rails', name: 'Rails', icon: null },
  { codeindex: 'asp-net', name: 'ASP.NET', icon: null },
  { codeindex: 'blazor', name: 'Blazor', icon: null },
  { codeindex: 'xamarin', name: 'Xamarin', icon: null },
  { codeindex: 'ionic', name: 'Ionic', icon: null },
  { codeindex: 'reactnative', name: 'React Native', icon: null },
  { codeindex: 'supabase', name: 'Supabase', icon: null },
  { codeindex: 'prisma', name: 'Prisma', icon: null },
  { codeindex: 'strapi', name: 'Strapi', icon: null },
  { codeindex: 'astro', name: 'Astro', icon: null },
  { codeindex: 'remix', name: 'Remix', icon: null },
  { codeindex: 'solidjs', name: 'SolidJS', icon: null },
  { codeindex: 'qwik', name: 'Qwik', icon: null },
  { codeindex: 'vite', name: 'Vite', icon: null },
  { codeindex: 'playwright', name: 'Playwright', icon: null },
  { codeindex: 'cypress', name: 'Cypress', icon: null },
  { codeindex: 'vitest', name: 'Vitest', icon: null },
  { codeindex: 'storybook', name: 'Storybook', icon: null },
  { codeindex: 'turborepo', name: 'Turborepo', icon: null },
  { codeindex: 'nx', name: 'Nx', icon: null },
  { codeindex: 'pnpm', name: 'PNPM', icon: null },
  { codeindex: 'bun', name: 'Bun', icon: null },
  { codeindex: 'deno', name: 'Deno', icon: null },
  { codeindex: 'trpc', name: 'tRPC', icon: null },
  { codeindex: 'grpc', name: 'gRPC', icon: null },
  { codeindex: 'rabbitmq', name: 'RabbitMQ', icon: null },
  { codeindex: 'elasticsearch', name: 'Elasticsearch', icon: null },
  { codeindex: 'cassandra', name: 'Cassandra', icon: null },
  { codeindex: 'mariadb', name: 'MariaDB', icon: null },
  { codeindex: 'oracle', name: 'Oracle', icon: null },
  { codeindex: 'mssql', name: 'Microsoft SQL Server', icon: null },
  { codeindex: 'dynamodb', name: 'DynamoDB', icon: null },
  { codeindex: 'snowflake', name: 'Snowflake', icon: null },
];
